/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiptRouteImport } from './routes/receipt'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'
import { Route as PublicNewsRouteImport } from './routes/_public.news'
import { Route as PublicCoursesRouteImport } from './routes/_public.courses'
import { Route as PublicContributeRouteImport } from './routes/_public.contribute'
import { Route as PublicContactRouteImport } from './routes/_public.contact'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as PublicCoursesIndexRouteImport } from './routes/_public.courses.index'
import { Route as AdminLayoutWebsiteRouteImport } from './routes/admin/_layout.website'
import { Route as AdminLayoutVolunteersRouteImport } from './routes/admin/_layout.volunteers'
import { Route as AdminLayoutTeamRouteImport } from './routes/admin/_layout.team'
import { Route as AdminLayoutReviewsRouteImport } from './routes/admin/_layout.reviews'
import { Route as AdminLayoutMessagesRouteImport } from './routes/admin/_layout.messages'
import { Route as AdminLayoutLinksRouteImport } from './routes/admin/_layout.links'
import { Route as AdminLayoutGalleryRouteImport } from './routes/admin/_layout.gallery'
import { Route as AdminLayoutDonorsRouteImport } from './routes/admin/_layout.donors'
import { Route as AdminLayoutDashboardRouteImport } from './routes/admin/_layout.dashboard'
import { Route as AdminLayoutCoursesRouteImport } from './routes/admin/_layout.courses'
import { Route as PublicCoursesIdRouteImport } from './routes/_public.courses.$id'

const ReceiptRoute = ReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicNewsRoute = PublicNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesRoute = PublicCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContributeRoute = PublicContributeRouteImport.update({
  id: '/contribute',
  path: '/contribute',
  getParentRoute: () => PublicRoute,
} as any)
const PublicContactRoute = PublicContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCoursesIndexRoute = PublicCoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicCoursesRoute,
} as any)
const AdminLayoutWebsiteRoute = AdminLayoutWebsiteRouteImport.update({
  id: '/website',
  path: '/website',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutVolunteersRoute = AdminLayoutVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutTeamRoute = AdminLayoutTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutReviewsRoute = AdminLayoutReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutMessagesRoute = AdminLayoutMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutLinksRoute = AdminLayoutLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutGalleryRoute = AdminLayoutGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDonorsRoute = AdminLayoutDonorsRouteImport.update({
  id: '/donors',
  path: '/donors',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutDashboardRoute = AdminLayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const AdminLayoutCoursesRoute = AdminLayoutCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminLayoutRoute,
} as any)
const PublicCoursesIdRoute = PublicCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PublicCoursesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/receipt': typeof ReceiptRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/contribute': typeof PublicContributeRoute
  '/courses': typeof PublicCoursesRouteWithChildren
  '/news': typeof PublicNewsRoute
  '/admin': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/$id': typeof PublicCoursesIdRoute
  '/admin/courses': typeof AdminLayoutCoursesRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/donors': typeof AdminLayoutDonorsRoute
  '/admin/gallery': typeof AdminLayoutGalleryRoute
  '/admin/links': typeof AdminLayoutLinksRoute
  '/admin/messages': typeof AdminLayoutMessagesRoute
  '/admin/reviews': typeof AdminLayoutReviewsRoute
  '/admin/team': typeof AdminLayoutTeamRoute
  '/admin/volunteers': typeof AdminLayoutVolunteersRoute
  '/admin/website': typeof AdminLayoutWebsiteRoute
  '/courses/': typeof PublicCoursesIndexRoute
}
export interface FileRoutesByTo {
  '/receipt': typeof ReceiptRoute
  '/about': typeof PublicAboutRoute
  '/contact': typeof PublicContactRoute
  '/contribute': typeof PublicContributeRoute
  '/news': typeof PublicNewsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/': typeof PublicIndexRoute
  '/courses/$id': typeof PublicCoursesIdRoute
  '/admin/courses': typeof AdminLayoutCoursesRoute
  '/admin/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/donors': typeof AdminLayoutDonorsRoute
  '/admin/gallery': typeof AdminLayoutGalleryRoute
  '/admin/links': typeof AdminLayoutLinksRoute
  '/admin/messages': typeof AdminLayoutMessagesRoute
  '/admin/reviews': typeof AdminLayoutReviewsRoute
  '/admin/team': typeof AdminLayoutTeamRoute
  '/admin/volunteers': typeof AdminLayoutVolunteersRoute
  '/admin/website': typeof AdminLayoutWebsiteRoute
  '/courses': typeof PublicCoursesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/receipt': typeof ReceiptRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/contact': typeof PublicContactRoute
  '/_public/contribute': typeof PublicContributeRoute
  '/_public/courses': typeof PublicCoursesRouteWithChildren
  '/_public/news': typeof PublicNewsRoute
  '/admin/_layout': typeof AdminLayoutRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/courses/$id': typeof PublicCoursesIdRoute
  '/admin/_layout/courses': typeof AdminLayoutCoursesRoute
  '/admin/_layout/dashboard': typeof AdminLayoutDashboardRoute
  '/admin/_layout/donors': typeof AdminLayoutDonorsRoute
  '/admin/_layout/gallery': typeof AdminLayoutGalleryRoute
  '/admin/_layout/links': typeof AdminLayoutLinksRoute
  '/admin/_layout/messages': typeof AdminLayoutMessagesRoute
  '/admin/_layout/reviews': typeof AdminLayoutReviewsRoute
  '/admin/_layout/team': typeof AdminLayoutTeamRoute
  '/admin/_layout/volunteers': typeof AdminLayoutVolunteersRoute
  '/admin/_layout/website': typeof AdminLayoutWebsiteRoute
  '/_public/courses/': typeof PublicCoursesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/receipt'
    | '/about'
    | '/contact'
    | '/contribute'
    | '/courses'
    | '/news'
    | '/admin'
    | '/admin/login'
    | '/admin/'
    | '/courses/$id'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/donors'
    | '/admin/gallery'
    | '/admin/links'
    | '/admin/messages'
    | '/admin/reviews'
    | '/admin/team'
    | '/admin/volunteers'
    | '/admin/website'
    | '/courses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/receipt'
    | '/about'
    | '/contact'
    | '/contribute'
    | '/news'
    | '/admin'
    | '/admin/login'
    | '/'
    | '/courses/$id'
    | '/admin/courses'
    | '/admin/dashboard'
    | '/admin/donors'
    | '/admin/gallery'
    | '/admin/links'
    | '/admin/messages'
    | '/admin/reviews'
    | '/admin/team'
    | '/admin/volunteers'
    | '/admin/website'
    | '/courses'
  id:
    | '__root__'
    | '/_public'
    | '/receipt'
    | '/_public/about'
    | '/_public/contact'
    | '/_public/contribute'
    | '/_public/courses'
    | '/_public/news'
    | '/admin/_layout'
    | '/admin/login'
    | '/_public/'
    | '/admin/'
    | '/_public/courses/$id'
    | '/admin/_layout/courses'
    | '/admin/_layout/dashboard'
    | '/admin/_layout/donors'
    | '/admin/_layout/gallery'
    | '/admin/_layout/links'
    | '/admin/_layout/messages'
    | '/admin/_layout/reviews'
    | '/admin/_layout/team'
    | '/admin/_layout/volunteers'
    | '/admin/_layout/website'
    | '/_public/courses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  ReceiptRoute: typeof ReceiptRoute
  AdminLayoutRoute: typeof AdminLayoutRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receipt': {
      id: '/receipt'
      path: '/receipt'
      fullPath: '/receipt'
      preLoaderRoute: typeof ReceiptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/news': {
      id: '/_public/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof PublicNewsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses': {
      id: '/_public/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof PublicCoursesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contribute': {
      id: '/_public/contribute'
      path: '/contribute'
      fullPath: '/contribute'
      preLoaderRoute: typeof PublicContributeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/contact': {
      id: '/_public/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof PublicContactRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/courses/': {
      id: '/_public/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof PublicCoursesIndexRouteImport
      parentRoute: typeof PublicCoursesRoute
    }
    '/admin/_layout/website': {
      id: '/admin/_layout/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AdminLayoutWebsiteRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/volunteers': {
      id: '/admin/_layout/volunteers'
      path: '/volunteers'
      fullPath: '/admin/volunteers'
      preLoaderRoute: typeof AdminLayoutVolunteersRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/team': {
      id: '/admin/_layout/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminLayoutTeamRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/reviews': {
      id: '/admin/_layout/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminLayoutReviewsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/messages': {
      id: '/admin/_layout/messages'
      path: '/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminLayoutMessagesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/links': {
      id: '/admin/_layout/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLayoutLinksRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/gallery': {
      id: '/admin/_layout/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminLayoutGalleryRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/donors': {
      id: '/admin/_layout/donors'
      path: '/donors'
      fullPath: '/admin/donors'
      preLoaderRoute: typeof AdminLayoutDonorsRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/dashboard': {
      id: '/admin/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminLayoutDashboardRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/admin/_layout/courses': {
      id: '/admin/_layout/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminLayoutCoursesRouteImport
      parentRoute: typeof AdminLayoutRoute
    }
    '/_public/courses/$id': {
      id: '/_public/courses/$id'
      path: '/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof PublicCoursesIdRouteImport
      parentRoute: typeof PublicCoursesRoute
    }
  }
}

interface PublicCoursesRouteChildren {
  PublicCoursesIdRoute: typeof PublicCoursesIdRoute
  PublicCoursesIndexRoute: typeof PublicCoursesIndexRoute
}

const PublicCoursesRouteChildren: PublicCoursesRouteChildren = {
  PublicCoursesIdRoute: PublicCoursesIdRoute,
  PublicCoursesIndexRoute: PublicCoursesIndexRoute,
}

const PublicCoursesRouteWithChildren = PublicCoursesRoute._addFileChildren(
  PublicCoursesRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicContactRoute: typeof PublicContactRoute
  PublicContributeRoute: typeof PublicContributeRoute
  PublicCoursesRoute: typeof PublicCoursesRouteWithChildren
  PublicNewsRoute: typeof PublicNewsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicContactRoute: PublicContactRoute,
  PublicContributeRoute: PublicContributeRoute,
  PublicCoursesRoute: PublicCoursesRouteWithChildren,
  PublicNewsRoute: PublicNewsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminLayoutRouteChildren {
  AdminLayoutCoursesRoute: typeof AdminLayoutCoursesRoute
  AdminLayoutDashboardRoute: typeof AdminLayoutDashboardRoute
  AdminLayoutDonorsRoute: typeof AdminLayoutDonorsRoute
  AdminLayoutGalleryRoute: typeof AdminLayoutGalleryRoute
  AdminLayoutLinksRoute: typeof AdminLayoutLinksRoute
  AdminLayoutMessagesRoute: typeof AdminLayoutMessagesRoute
  AdminLayoutReviewsRoute: typeof AdminLayoutReviewsRoute
  AdminLayoutTeamRoute: typeof AdminLayoutTeamRoute
  AdminLayoutVolunteersRoute: typeof AdminLayoutVolunteersRoute
  AdminLayoutWebsiteRoute: typeof AdminLayoutWebsiteRoute
}

const AdminLayoutRouteChildren: AdminLayoutRouteChildren = {
  AdminLayoutCoursesRoute: AdminLayoutCoursesRoute,
  AdminLayoutDashboardRoute: AdminLayoutDashboardRoute,
  AdminLayoutDonorsRoute: AdminLayoutDonorsRoute,
  AdminLayoutGalleryRoute: AdminLayoutGalleryRoute,
  AdminLayoutLinksRoute: AdminLayoutLinksRoute,
  AdminLayoutMessagesRoute: AdminLayoutMessagesRoute,
  AdminLayoutReviewsRoute: AdminLayoutReviewsRoute,
  AdminLayoutTeamRoute: AdminLayoutTeamRoute,
  AdminLayoutVolunteersRoute: AdminLayoutVolunteersRoute,
  AdminLayoutWebsiteRoute: AdminLayoutWebsiteRoute,
}

const AdminLayoutRouteWithChildren = AdminLayoutRoute._addFileChildren(
  AdminLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  ReceiptRoute: ReceiptRoute,
  AdminLayoutRoute: AdminLayoutRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
